name: Deploy arkastech.com to Server

on:
  push:
    branches:
      - main
    paths:
      - "arkastech/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 72.60.26.170
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/arkastech.com
            rsync -avz --delete /tmp/arkastech/ ./
            systemctl restart nginx
            echo "Despliegue de arkastech.com completado exitosamente"

      - name: Sync files to server
        uses: appleboy/scp-action@master
        with:
          host: 72.60.26.170
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "arkastech/*"
          target: "/tmp/"
          strip_components: 1
