name: Deploy arkastech.com to Server

on:
  push:
    branches:
      - main
    paths:
      - "arkastech.com/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to server
        uses: appleboy/scp-action@master
        with:
          host: 72.60.26.170
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "arkastech.com/*"
          target: "/var/www/html/"
          strip_components: 1

      - name: Restart nginx
        uses: appleboy/ssh-action@master
        with:
          host: 72.60.26.170
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl reload nginx
            echo "Despliegue de arkastech.com completado exitosamente"
